---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 4833723535-7hfNDb6SFul6V0WZUxAPDENER1BtqnOkINRXj5V
:access_token_secret: dM1sJGkwbXdU5iVwt8BSATIiIy0pyphfEG5VuQSHvMU6X
